name: vitessce-demo-sc-atac-seq-10x-genomics
channels:
  - conda-forge
  - bioconda
  - scottx611x
dependencies:
  - python>=3.5
  - numpy
  - pandas
  - requests
  - h5py
  - dask
  - flake8
  - autopep8
  - pysam
  - snakemake
  - scipy
  - scikit-learn
  - pyBigWig
  - pytables
  - zarr
  - numcodecs
  - tqdm
  - pip
  - pip:
    - negspy
    - slugid
    - sortedcontainers
    - nose
    - cooler>=0.8.5
    - click>=7
    - pytest
    - pytest-cov
    - bumpversion
    - pybbi>=0.2.3
    - clodius